Repository mumu-lhl/Ciyue, pull requests merged in 2025-01, with the labels that each got.

#104 feat: group dictionaries
  drift_schemas/app/drift_schema_v6.json
  lib/database/app.dart
  lib/database/app.g.dart
  lib/database/app.steps.dart
  lib/dictionary.dart
  lib/main.dart
  lib/pages/main/main.dart
  lib/pages/main/settings.dart
  lib/pages/manage_dictionaries/main.dart
  lib/pages/webview_display.dart
  test/drift/app/generated/schema.dart
  test/drift/app/generated/schema_v6.dart
Labels: enhancement

#108 feat: remove external storage permission
  android/app/build.gradle
  android/app/src/main/kotlin/org/eu/mumulhl/ciyue/MainActivity.kt
  android/build.gradle
  android/settings.gradle
  lib/main.dart
  lib/pages/manage_dictionaries/main.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, breaking-change

#116 fix: export workbook
  android/app/src/main/kotlin/org/eu/mumulhl/ciyue/MainActivity.kt
  lib/pages/main/settings.dart
Labels: bug

#119 feat: add loading dialog when adding dictionaries
  android/app/src/main/kotlin/org/eu/mumulhl/ciyue/MainActivity.kt
  lib/main.dart
  lib/pages/manage_dictionaries/main.dart
Labels: enhancement

#125 feat: add auto remove search word feature
  lib/l10n/app_en.arb
  lib/l10n/app_fa.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_sc.arb
  lib/l10n/app_ta.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_HK.arb
  lib/l10n/app_zh_TW.arb
  lib/pages/main/home.dart
  lib/pages/main/main.dart
  lib/settings.dart
Labels: enhancement

#126 feat: handle removal of missing dictionary files
  lib/dictionary.dart
Labels: enhancement

#127 feat: implement tag ordering
  lib/database/app.dart
  lib/main.dart
  lib/pages/main/wordbook.dart
Labels: enhancement

#134 feat(translation): translations update from Hosted Weblate
  lib/l10n/app_de.arb
Labels: enhancement

#139 fix: Anti-Screenshots become ineffective every time Ciyue is reopened
  lib/main.dart
  lib/pages/auto_export.dart
  lib/pages/main/settings.dart
  lib/pages/manage_dictionaries/main.dart
  lib/pages/webview_display.dart
  lib/platform.dart
Labels: bug

#141 feat: implement HTTP server for Windows and update webview handling
  lib/dictionary.dart
  lib/pages/webview_display.dart
Labels: enhancement

#145 feat: add search bar location setting
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_fa.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_sc.arb
  lib/l10n/app_ta.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_HK.arb
  lib/l10n/app_zh_TW.arb
  lib/main.dart
  lib/pages/main/main.dart
  lib/pages/main/settings.dart
  lib/settings.dart
Labels: enhancement

#149 feat: add sidebar icon toggle
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_fa.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_sc.arb
  lib/l10n/app_ta.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_HK.arb
  lib/l10n/app_zh_TW.arb
  lib/main.dart
  lib/pages/main/main.dart
  lib/pages/main/settings.dart
  lib/settings.dart
Labels: enhancement

#151 feat: implement dismissible history items
  lib/pages/main/home.dart
Labels: enhancement
