Repository mumu-lhl/Ciyue, pull requests merged in 2025-03, with the labels that each got.

#201 feat(ui): group settings
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_fa.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_sc.arb
  lib/l10n/app_ta.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_HK.arb
  lib/l10n/app_zh_TW.arb
  lib/pages/main/settings.dart
Labels: enhancement

#202 fix: context menu search doesn't work with capitalized word
  lib/database/dictionary.dart
Labels: bug

#203 feat: add words to the wordbook with the date
  drift_schemas/app/drift_schema_v8.json
  lib/database/app.dart
  lib/database/app.g.dart
  lib/database/app.steps.dart
  lib/pages/main/wordbook.dart
  lib/widget/date_divider.dart
  test/drift/app/generated/schema.dart
  test/drift/app/generated/schema_v8.dart
Labels: enhancement

#216 fix: fix word's date in wordbook
  drift_schemas/app/drift_schema_v9.json
  lib/database/app.dart
  lib/database/app.g.dart
  lib/database/app.steps.dart
  lib/pages/main/settings.dart
  test/drift/app/generated/schema.dart
  test/drift/app/generated/schema_v9.dart
Labels: bug

#217 fix: filter duplicate search results
  lib/pages/main/home.dart
Labels: bug

#218 fix: fix Sardinian
  lib/localization_delegates.dart
  lib/main.dart
Labels: bug

#219 refactor(ui): refactor dynamic color
  lib/main.dart
Labels: enhancement

#220 refactor: show more recommended dictionaries
  lib/pages/main/home.dart
  lib/pages/manage_dictionaries/main.dart
Labels: enhancement

#228 feat: add AI translate
  lib/ai.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/pages/main/ai_translate_page.dart
  lib/pages/main/main.dart
  lib/pages/main/settings.dart
  lib/pages/settings/ai_settings.dart
  lib/pages/settings/auto_export.dart
  lib/settings.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#226 chore(ci): add Linux build to workflow
  .github/workflows/flutter.yml
  .github/workflows/release.yml
Labels: enhancement

#229 feat: add Privacy Policy
  lib/l10n/app_en.arb
  lib/main.dart
  lib/pages/main/settings.dart
  lib/pages/settings/privacy_policy.dart
Labels: enhancement

#231 feat: add Terms of Service
  lib/l10n/app_en.arb
  lib/main.dart
  lib/pages/main/settings.dart
  lib/pages/settings/privacy_policy.dart
  lib/pages/settings/terms_of_service.dart
Labels: enhancement

#232 feat: add more models
  lib/ai.dart
  lib/pages/settings/ai_settings.dart
  lib/settings.dart
Labels: enhancement

#237 chore(deps): replace flutter_markdown with gpt_markdown
  lib/pages/main/ai_translate_page.dart
  lib/pages/settings/privacy_policy.dart
  lib/pages/settings/terms_of_service.dart
  package.json
  pnpm-lock.yaml
  pubspec.lock
  pubspec.yaml
Labels: dependencies

#238 fix: blank screen when editing title alias of a disabled dict
  lib/pages/manage_dictionaries/main.dart
Labels: bug

#239 feat: enable explain word
  lib/pages/main/home.dart
  lib/pages/main/main.dart
  lib/pages/settings/ai_settings.dart
  lib/pages/webview_display.dart
Labels: enhancement

#240 feat: add check for updates functionality in settings
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_fa.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_sc.arb
  lib/l10n/app_ta.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_HK.arb
  lib/l10n/app_zh_TW.arb
  lib/main.dart
  lib/pages/main/settings.dart
  lib/settings.dart
Labels: enhancement

#247 refactor: refactor the code of home
  android/.gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  android/settings.gradle
  lib/main.dart
  lib/pages/main/home.dart
  lib/pages/main/main.dart
  lib/pages/webview_display.dart
  lib/platform.dart
Labels: enhancement

#248 fix: fix remove single history twice
  lib/pages/main/home.dart
Labels: enhancement

#249 refactor: refactor main page and history list
  lib/main.dart
  lib/pages/main/ai_translate_page.dart
  lib/pages/main/home.dart
  lib/pages/main/main.dart
  lib/pages/main/wordbook.dart
  lib/pages/manage_dictionaries/main.dart
  lib/pages/settings/ai_settings.dart
  lib/pages/webview_display.dart
  pnpm-lock.yaml
  pubspec.lock
  pubspec.yaml
Labels: enhancement
