Repository mumu-lhl/Ciyue, pull requests merged in 2025-05, with the labels that each got.

#304 feat: auto update
  lib/l10n/app_en.arb
  lib/main.dart
  lib/models/updater.dart
  lib/models/updater.freezed.dart
  lib/pages/main/settings.dart
  lib/services/updater.dart
  lib/settings.dart
  lib/widget/update_available.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#307 feat(translation): translations update from Hosted Weblate
  lib/l10n/app_ca.arb
  lib/l10n/app_es.arb
Labels: enhancement

#308 refactor: improve export feature
  lib/l10n/app_en.arb
  lib/models/backup/backup.dart
  lib/pages/main/settings.dart
  lib/pages/word_display.dart
  lib/services/backup.dart
Labels: enhancement

#309 feat(translation): support Catalan (Thanks to @fitojb)
  lib/l10n/app_ca.arb
Labels: enhancement

#319 refactor(ui): improve search ui
  lib/database/dictionary.dart
  lib/pages/main/home.dart
  lib/pages/word_display.dart
  lib/services/platform.dart
  lib/utils.dart
  lib/viewModels/home.dart
Labels: enhancement

#322 fix(ui): fix focus
  android/app/build.gradle.kts
  lib/pages/main/home.dart
  lib/pages/main/main.dart
  lib/pages/settings/ai_settings.dart
  lib/pages/word_display.dart
  lib/services/platform.dart
  lib/viewModels/home.dart
Labels: bug

#320 chore: adjust version code
  android/app/build.gradle.kts
Labels: bug

#325 feat: add audio settings
  lib/l10n/app_en.arb
  lib/main.dart
  lib/pages/main/settings.dart
  lib/pages/settings/audio.dart
  lib/services/settings.dart
Labels: enhancement

#327 fix: search result
  lib/main.dart
  lib/pages/main/home.dart
  lib/pages/main/settings.dart
  lib/pages/word_display.dart
  lib/widget/search_bar.dart
Labels: bug

#328 feat(model): update Gemini 2.5 Pro to the latest
  lib/services/ai.dart
Labels: enhancement

#329 feat(ai): support OpenAI Compatible and Ollama as providers
  lib/l10n/app_en.arb
  lib/models/ai/ai.dart
  lib/models/ai/ai.freezed.dart
  lib/pages/settings/ai_settings.dart
  lib/services/ai.dart
  lib/services/settings.dart
Labels: enhancement

#330 feat: implement floating window
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/org/eu/mumulhl/ciyue/FloatingWindowService.kt
  android/app/src/main/kotlin/org/eu/mumulhl/ciyue/MainActivity.kt
  android/app/src/main/kotlin/org/eu/mumulhl/ciyue/ProcessTextActivity.kt
  lib/l10n/app_en.arb
  lib/main.dart
  lib/pages/main/settings.dart
  lib/pages/word_display.dart
  lib/services/platform.dart
Labels: enhancement

#341 refactor(manage dictionaries): enhance dictionary management features and improve state handling
  lib/main.dart
  lib/pages/manage_dictionaries/main.dart
  lib/pages/manage_dictionaries/properties.dart
  lib/services/dictionary.dart
  lib/services/platform.dart
  lib/viewModels/dictionary.dart
Labels: enhancement

#342 feat(ai translate): add Hindi language
  lib/pages/main/ai_translate_page.dart
Labels: enhancement

#343 fix: history
  lib/viewModels/home.dart
  lib/widget/search_bar.dart
Labels: bug

#338 feat(translation): translations update from Hosted Weblate
  lib/l10n/app_fa.arb
Labels: translation

#344 feat: support add mutiple dictionaries at once
  lib/l10n/app_en.arb
  lib/pages/manage_dictionaries/main.dart
  lib/services/dictionary.dart
Labels: enhancement

#345 fix: set windows webview2 directory
  lib/main.dart
  lib/pages/word_display.dart
Labels: bug

#346 fix: only show floating window when permission is enabled
  android/app/src/main/kotlin/org/eu/mumulhl/ciyue/ProcessTextActivity.kt
Labels: bug

#349 feat: new default explanation prompt
  lib/pages/word_display.dart
Labels: enhancement

#350 refactor(animation): refacotr page transition
  lib/main.dart
  lib/pages/manage_dictionaries/main.dart
Labels: enhancement

#351 fix: add dictionary on Android
  lib/services/platform.dart
Labels: bug

#355 Add Claude 4
  lib/services/ai.dart
Labels: enhancement

#358 Refactor AI Explain Word
  lib/pages/word_display.dart
  lib/widget/ai_markdown.dart
Labels: enhancement

#360 Support adding custom audio resources
  android/app/src/main/kotlin/org/eu/mumulhl/ciyue/MainActivity.kt
  build.yaml
  devtools_options.yaml
  drift_schemas/app/drift_schema_v10.json
  lib/database/app/app.dart
  lib/database/app/app.g.dart
  lib/database/app/app.steps.dart
  lib/database/app/daos.dart
  lib/database/app/daos.g.dart
  lib/database/app/tables.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/pages/main/settings.dart
  lib/pages/manage_dictionaries/main.dart
  lib/pages/settings/audio.dart
  lib/pages/word_display.dart
  lib/services/audio.dart
  lib/services/dictionary.dart
  lib/services/platform.dart
  lib/viewModels/audio.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  pubspec.lock
  pubspec.yaml
  test/drift/app/generated/schema.dart
  test/drift/app/generated/schema_v10.dart
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement

#362 feat: fake webview for linux
  lib/pages/word_display.dart
Labels: enhancement

#367 refactor(translation): migrate i18n placeholders to named arguments
  lib/l10n/app_bn.arb
  lib/l10n/app_ca.arb
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fa.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_sc.arb
  lib/l10n/app_ta.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_HK.arb
  lib/l10n/app_zh_TW.arb
  lib/pages/main/home.dart
  lib/services/dictionary.dart
  lib/widget/update_available.dart
Labels: translation

#369 fix: fix anthropic url
  lib/services/ai.dart
Labels: bug

#371 chore: support AppImage
  .github/workflows/release.yml
  .gitignore
  AppImageBuilder.yml
Labels: enhancement

#375 feat: add more languages on translate page
  lib/pages/main/ai_translate_page.dart
Labels: enhancement
