Repository mumu-lhl/Ciyue, pull requests merged in 2025-04, with the labels that each got.

#253 refactor: replace context.select with Consumer
  lib/pages/main/wordbook.dart
Labels: enhancement

#254 feat: support navigation rail
  lib/pages/main/main.dart
Labels: enhancement

#255 docs: add sponsors section to README files
  README.md
  README_CN.md
Labels: documentation

#258 refactor: constrain maximum width in settings, auto export and dictio…
  lib/pages/manage_dictionaries/main.dart
  lib/pages/settings/ai_settings.dart
  lib/pages/settings/auto_export.dart
Labels: enhancement

#259 fix: TabBarView
  lib/pages/webview_display.dart
Labels: bug

#260 feat: add error handling and reporting UI before running
  lib/main.dart
Labels: enhancement

#261 fix(focus): wrap IndexedStack pages with FocusScope to fix restoration
  lib/pages/main/main.dart
Labels: bug

#263 chore(release): add windows installer
  .github/workflows/release.yml
  ciyue.iss
Labels: enhancement

#264 fix: cannot running app after removing cache
  lib/dictionary.dart
Labels: bug

#266 refactor: refactor TextField
  lib/pages/main/home.dart
  lib/pages/main/wordbook.dart
  lib/pages/manage_dictionaries/main.dart
  lib/pages/settings/auto_export.dart
Labels: enhancement

#267 feat: support custom prompts
  lib/main.dart
  lib/pages/main/ai_translate_page.dart
  lib/pages/settings/ai_settings.dart
  lib/pages/webview_display.dart
  lib/settings.dart
Labels: enhancement

#268 feat(language): support Bengali language (Thanks to Ekramul Reza)
  lib/pages/main/settings.dart
Labels: enhancement

#277 chore(release): fix installer path in release workflow
  .github/workflows/release.yml
Labels: enhancement

#278 fix(ui): instantly update UI when deleting or auto-removing search terms
  lib/pages/main/home.dart
Labels: bug

#279 refactor: copy files to support path on Android
  android/app/build.gradle
  android/app/src/main/kotlin/org/eu/mumulhl/ciyue/MainActivity.kt
  lib/platform.dart
Labels: enhancement

#280 refactor(ui): make TabBar horizontally scrollable to prevent tab over…
  lib/pages/webview_display.dart
Labels: enhancement

#281 feat: add TabBar position setting
  lib/l10n/app_bn.arb
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fa.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_sc.arb
  lib/l10n/app_ta.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_HK.arb
  lib/l10n/app_zh_TW.arb
  lib/main.dart
  lib/pages/main/settings.dart
  lib/pages/webview_display.dart
  lib/settings.dart
Labels: enhancement

#282 feat(ui): set NavigationRail to extended state in wide landscape
  lib/pages/main/main.dart
Labels: enhancement

#288 feat: add more AI models and AI providers
  lib/ai.dart
  lib/pages/settings/ai_settings.dart
  lib/settings.dart
Labels: enhancement

#290 Web docs
  .github/workflows/flutter.yml
  .github/workflows/vitepress-deploy.yml
  README.md
  README_CN.md
  docs/.gitignore
  docs/.vitepress/config.mts
  docs/guide/getting-started.md
  docs/guide/index.md
  docs/index.md
  docs/package.json
  docs/pnpm-lock.yaml
  docs/pnpm-workspace.yaml
  package.json
Labels: documentation

#291 feat: delete associated .mdx and .mdd files on dictionary removal for…
  lib/dictionary.dart
Labels: enhancement

#294 feat: enhance loading dialog with dynamic text updates and refactor s…
  lib/dictionary.dart
  lib/pages/manage_dictionaries/main.dart
  lib/widget/loading_dialog.dart
Labels: enhancement

#295 feat: add search bar functionality in word display
  lib/l10n/app_bn.arb
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fa.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_sc.arb
  lib/l10n/app_ta.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_HK.arb
  lib/l10n/app_zh_TW.arb
  lib/main.dart
  lib/pages/main/home.dart
  lib/pages/main/settings.dart
  lib/pages/webview_display.dart
  lib/settings.dart
Labels: enhancement
