Repository mumu-lhl/Ciyue, pull requests merged in 2025-02, with the labels that each got.

#153 fix: fix update button in manage dictionaries page
  android/app/build.gradle
  android/app/src/main/kotlin/org/eu/mumulhl/ciyue/MainActivity.kt
  lib/database/app.dart
  lib/main.dart
  lib/pages/manage_dictionaries/main.dart
  lib/platform.dart
Labels: bug

#154 fix: disable scroll on TabBarView in WebviewDisplay
  lib/pages/webview_display.dart
Labels: bug

#157 fix: fix deleting dictionary
  lib/pages/manage_dictionaries/main.dart
Labels: bug

#161 feat: allow edit word when views word from process text
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_fa.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_sc.arb
  lib/l10n/app_ta.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_HK.arb
  lib/l10n/app_zh_TW.arb
  lib/main.dart
  lib/pages/main/main.dart
  lib/pages/webview_display.dart
Labels: enhancement

#163 feat: add German and Sardinian language options to settings
  lib/pages/main/settings.dart
Labels: enhancement

#164 fix: show bottom search bar on wrongly screens
  lib/pages/main/main.dart
Labels: bug

#165 feat: add notification for searching fastly
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_fa.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_sc.arb
  lib/l10n/app_ta.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_HK.arb
  lib/l10n/app_zh_TW.arb
  lib/main.dart
  lib/pages/main/home.dart
  lib/pages/main/main.dart
  lib/pages/main/settings.dart
  lib/pages/webview_display.dart
  lib/platform.dart
  lib/settings.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#167 feat: add title alias
  drift_schemas/app/drift_schema_v7.json
  lib/database/app.dart
  lib/database/app.g.dart
  lib/database/app.steps.dart
  lib/dictionary.dart
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_fa.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_sc.arb
  lib/l10n/app_ta.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_HK.arb
  lib/l10n/app_zh_TW.arb
  lib/pages/manage_dictionaries/main.dart
  lib/pages/webview_display.dart
  test/drift/app/generated/schema.dart
  test/drift/app/generated/schema_v7.dart
Labels: enhancement

#168 feat: add option to skip tagged words in word book
  lib/database/app.dart
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_fa.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_sc.arb
  lib/l10n/app_ta.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_HK.arb
  lib/l10n/app_zh_TW.arb
  lib/main.dart
  lib/pages/main/wordbook.dart
  lib/settings.dart
Labels: enhancement

#169 feat: add option to switch show not found words
  lib/database/dictionary.dart
  lib/dictionary.dart
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_fa.arb
  lib/l10n/app_nb.arb
  lib/l10n/app_ru.arb
  lib/l10n/app_sc.arb
  lib/l10n/app_ta.arb
  lib/l10n/app_zh.arb
  lib/l10n/app_zh_HK.arb
  lib/l10n/app_zh_TW.arb
  lib/main.dart
  lib/pages/main/settings.dart
  lib/pages/manage_dictionaries/main.dart
  lib/pages/webview_display.dart
  lib/settings.dart
Labels: enhancement

#178 fix: optimize word addition logic
  lib/database/app.dart
  lib/pages/webview_display.dart
Labels: bug

#189 fix: fix can't add word with tags
  lib/main.dart
  lib/pages/webview_display.dart
Labels: bug

#190 feat: support selecting tags for adding words to wordbook at home page
  lib/pages/main/home.dart
  lib/pages/webview_display.dart
  lib/widget/tags_list.dart
Labels: enhancement

#183 UI tweaks
  lib/main.dart
  lib/pages/main/home.dart
  lib/pages/main/main.dart
  lib/pages/webview_display.dart
Labels: enhancement

#192 feat: add Discord link
  lib/pages/main/settings.dart
Labels: enhancement

#196 refactor: don't show not found dictionaries defaultly
  lib/main.dart
  lib/pages/main/settings.dart
  lib/pages/webview_display.dart
  lib/settings.dart
Labels: bug, enhancement

#197 fix: display title when title in header is empty string
  lib/dictionary.dart
Labels: bug
