Repository mumu-lhl/Ciyue, pull requests merged in 2025-08, with the labels that each got.

#478 Fix local audio play
  lib/ui/core/word_display.dart
Labels: bug

#482 Fix light mode webview display
  lib/ui/core/word_display.dart
Labels: bug

#486 UI: Use flutter_smart_dialog to provide toast
  lib/core/app_router.dart
  lib/main.dart
  lib/repositories/dictionary.dart
  lib/services/toast.dart
  lib/ui/pages/main/main.dart
  lib/ui/pages/settings/about.dart
  lib/ui/pages/settings/manage_dictionaries/main.dart
  lib/ui/pages/settings/storage_management.dart
  lib/ui/pages/settings/update.dart
  lib/utils.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#488 feat(translation): translations update from Hosted Weblate
  lib/l10n/app_got.arb
Labels: translation

#493 Fix resource loading
  lib/repositories/dictionary.dart
  lib/ui/core/word_display.dart
Labels: bug

#494 Perf: Speed loading word display page up
  lib/repositories/dictionary.dart
  lib/ui/core/word_display.dart
  pubspec.lock
  pubspec.yaml
Labels: performance

#495 Perf: Reduce initialization time
  lib/repositories/dictionary.dart
  lib/services/audio.dart
  pubspec.lock
  pubspec.yaml
Labels: performance

#503 Cache dictionaries initial information
  lib/repositories/dictionary.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#504 Fix multiple content of same words
  lib/repositories/dictionary.dart
  lib/ui/core/word_display.dart
  pubspec.lock
  pubspec.yaml
Labels: bug

#509 Perf: Reduce initialization time
  android/app/build.gradle.kts
  lib/core/app_initialization.dart
  lib/repositories/dictionary.dart
  lib/ui/pages/settings/manage_dictionaries/main.dart
  lib/viewModels/dictionary.dart
Labels: performance

#512 Full: Fix request storage permission on below Android 13
  lib/utils.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, android

#538 Fix search bar when set to bottom
  lib/repositories/dictionary.dart
  lib/ui/pages/main/home/search.dart
  lib/viewModels/dictionary.dart
Labels: bug
